### PR TITLE
Compile-time case, CMake, and more

### PR DESCRIPTION
**Pull request by henryleberre**
This pull request includes:
- A switch to the CMake build system generator to improve:
  - Handle cross-platform compilations (\*nix, macOS, and (partially) Windows).
  - Dependency management (fetches and compiles dependencies).
  - Locating, finding, and using libraries and compiler features (e.g. MPI, OpenACC, Link Time Optimization (LTO/IPO)).
  - Support of various compilers & set their flags.
  - Handling of Fypp pre-processing (without copying directories and time-data).
  - Maintainability of the build system. 
  - Included LLNL/Silo#262
- The inclusion of the case one wishes to run at compile-time to improve performance. Thus, a new case scheme has been conceived in Python to represent a Case, using an object oriented approach with the support of enumerations.
- Regular and OpenACC-accelerated build targets co-exist. This effectively "merges" the master and GPU branches.
- Fypp now generates `.f90` files to an easily-accessible `src/<code name>/autogen` folder.
- A Docker container environment to build/test MFC regardless of host operating system.
  - I currently host a Docker image on DockerHub ([here](https://hub.docker.com/repository/docker/henryleberre/mfc))
- The README has collapsible (and collapsed) sections to only show information that is relevant to the user.
- Tests no longer attempt to use `srun`. 
- Files that were generally shared between codes have been merged and moved to `src/common`. These include the following modules:
  - `m_compile_specific`
  - `m_derived_types`
  - `m_global_parameters`
  - `m_mpi_proxy`
- The Python CLI interface has been converted into a Python module that is installed with `pip` upon the first execution of `mfc.sh`. This lets users write `from mfc.case import *` in order to write their case description files.
- The Batch execution engine for `mfc.sh run` now forwards loaded modules when generating the final batch script from the templates.

The following GitHub issues will be resolved:
- #131: We switched to CMake.
- #113: @anandrdbz added cuFFT.
- #106: Cuda is no longer a dependency when not using OpenACC.
- #18: `src/common` was created, though, we can do more in the future (e.g `m_variables_conversion`).

Testing Progress:
- Local machine (x86-64, WSL 2 on Arch Linux) ✅
- ORNL Summit ✅
- SDSC Expanse ⚠️ (Python doesn't work properly)
- PSC Bridges2 (with manually built CMake) ✅
- GT Wingtip#3 (with manually built CMake) ✅
- Richardson 🧪
  - Not tested, my IP has changed.

Credit: @henryleberre and @anandrdbz.

### CODE REVIEW

**Comment by henryleberre** [comment]
@sbryngelson I fixed the issue that caused tests to fail and replaced the `--no-dependencies` option for a series of `--no-<target name>` options. They are automatically created for dependencies. MFC does run on Phoenix provided you use Spack for a non-ancient version of Python. (Serializing the case for F90 did require the use of "newer" Python type-hinting features).

**Comment by sbryngelson** [comment]
Several problems with this pull request:

* switch to Cmake means we cannot build Silo on MacOS
* opaque build means the user doesn't know if the code is built or not (or if it was built properly, or how it was built, or anything of that kind)
* tests take a very long time on the user's computer. previously they only took a few minutes. users won't be willing to wait two hours for tests to complete on their machine.
* most cases in `samples/` don't work and fail immediately 
* most cases in `samples/` don't have any physical meaning (so what are they samples of?)
* `toolchain/` build system has ballooned to 2398 Python SLOC. need to remove most of this bloat as this level of build system complexity is long-run unmaintainable

**Comment by henryleberre** [comment]
Thank you @sbryngelson for your comments and concerns, some of which I did share.

- The Silo issue was _most probably_ caused by updating Silo, as the error also appears when using autotools. I submitted a fix to Silo in both their CMake and Autotools-based build system generators: LLNL/Silo#267.
- `toolchain` has grown in size for two reasons:
  - :arrow_upper_right: @anandrdbz Included by accident a copy of `cases.py` from the test suite he was referring to (326 LOC). I can delete it.
  - :arrow_upper_right: `case.py` which describes the case, handles some preprocessing, and serializes types to Fortran is large (619 LOC) compared to other files. Most lines are purely describing structures and don't contain logic.
  - :arrow_upper_right: Looking at the LOC present in the `toolchain` folder includes more than what was previously in `bootstrap`. It contains the template files for batch submission, the Dockerfile, and `load.sh`.
  - :arrow_lower_right: All files related to building MFC have drastically shrinked in size, and some have been removed, as CMake let me reimplement it in a more standard manner, requiring less maintenance and _original_ code.
- If we keep this approach, your other points could be resolved:
  - **Testing**:
    - **Duration: (better) Multithreading**:
      - **Problem**: Currently, all threads given to `./mfc.sh` by way of the `-j` option are given to the compiler of a single case. Thus, most of the time taken to run a case is spent on a single thread, while linking, preprocessing, and running MFC (except for `ppn=2` cases). Further, compilation will most certainly not use all available threads as very few files need to be Fypp'd and recompiled, and depend on each other. This isn't too different with how we started running tests until I made them run in parallel.
      - **Solution**: Have each thread maintain its own build of MFC which it runs tests with. This would alleviate the problems above.
    - **_opaqueness_**:
      - **Problem**: When you run `./mfc.sh test -j $(nproc)` for the first time, it can take quite a while to build `pre_process`, `simulation`, and their dependencies. Thus, the user might believe MFC has hung. 
      - **Solution**: Remove about 5 characters from the toolchain code so that the build output is displayed in real time. You get the configure output from CMake, the build output from your build system (GNU Make / Ninja), and the "run" output from `./mfc.sh run`. There is an easy way for this solution and the previous to coexist: Show dependencies building first using all threads, and then the testing status for all threads should be enough to show the user work is being done.
  - **Build _opaqueness_**: 
    - **Problem**: There isn't the notion of a "build of MFC" anymore, which may spark fear to those who have established `./mfc.sh build` as a safe-haven from the tyrannic rule of unstable build environments when one wishes not to save the modules that work with MFC. Further, it may be confusing for a code to not be "buildable" without a case. This is a tricky problem to tackle, and can very much be a matter of personal taste. One can see this system as a convenient abstraction for users, as it hides the build process, only exposing verbs that would interest them such as `run` and `test`.
    - _**Solution**_: A partial solution could be to provide a "default" `case.fpp` file so that you could compile it, perhaps all with `dflt_int` and `dflt_real` values. Another solution which I previously mentioned would be to support both use-cases:
      - Compiling once and reading from an input file
      - Compiling with a case 

As @sbryngelson mentioned the key component in whether we keep this approach is performance. @anandrdbz indicated he believed that the performance benefit would be worthwhile. He hardcoded some parameters to increase performance in his GPU runs. It would be great if we could do a _fair and unbiased_ benchmark to assess the merits of this admittedly more involved approach. But I agree with @anandrdbz that we would expect a notable increase in performance for GPU cases. 

Note: Many parameters have been introduced to the code at compile-time but some remain defined at runtime.

**Comment by sbryngelson** [comment]
```
Currently, all threads given to ./mfc.sh by way of the -j option are given to the compiler of a single case. Thus, most of the time taken to run a case is spent on a single thread, while linking, preprocessing, and running MFC (except for ppn=2 cases). Further, compilation will most certainly not use all available threads as very few files need to be Fypp'd and recompiled, and depend on each other. This isn't too different with how we started running tests until I made them run in parallel.
```

I don't think we should count on users to be running the tests in massive parallelism. Most of this will occur in a login node of a supercomputer, which might not like them using more than a couple of cores at once (nor should they use more). 

```
Solution: Remove about 5 characters from the toolchain code so that the build output is displayed in real-time. You get the configure output from CMake, the build output from your build system (GNU Make / Ninja), and the "run" output from ./mfc.sh run. There is an easy way for this solution and the previous to coexist: Show dependencies building first using all threads, and then the testing status for all threads should be enough to show the user work is being done.
```

I don't think any of this should be tackled until we establish the performance differences between the cases described below

```
As @sbryngelson mentioned the key component in whether we keep this approach is performance. @anandrdbz indicated he believed that the performance benefit would be worthwhile. He hardcoded some parameters to increase performance in his GPU runs. It would be great if we could do a fair and unbiased benchmark to assess the merits of this admittedly more involved approach. But I agree with @anandrdbz that we would expect a notable increase in performance for GPU cases.
```

**Pull request closed without merging**
