### PR TITLE
CMake, `--case-optimization`, master--GPU merge, and more

### LINKED ISSUE #18: Shared modules
I'm not sure there's any good reason that pre_process, simulation, and post_process can't share some subroutines (like variable_conversion, mpi_proxy, etc.).

Common subroutines should be coalesced into a shared module directory, though this should be done carefully as there might be some minor differences between codes.

Again: **This should not be addressed until `GPU-3D-unmanaged` is merged into `master`**

### LINKED ISSUE #21: Doxygen problems: script + CI + badge
* Need a script that auto-builds the Doxygen documentation on CI and adds a README badge.
* Doxygen will require graphviz (or something like this) to build the documentation properly.
* Right now Doxygen will complain that `../icon.ico` is missing. I don't remember what the icon ever was, so we can remove it for now.
* The landing page of the Doxygen involves a lot of HTML that just repeats what is already in the readme. Not DRY!
* The Doxygen is also copied over to the website located here mfc-caltech.github.io which has a repository here: https://github.com/MFC-Caltech/MFC-Caltech.github.io, again not DRY

### LINKED ISSUE #106: GPU branch requires CUDA, even in CPU mode
Cannot compile GPU branch in CPU mode without CUDA, nvhpc, etc. This will have to be fixed, since it will soon be the `master` branch and must be compatible for most folks, including CPU-only users. Fix might include using `fypp` or macros.

### LINKED ISSUE #113: GPU branch removed fft!
Need to put an FFT back into the GPU branch for `cyl_coords` (see `fftw.f90` on master branch).

### LINKED ISSUE #131: Issue building HDF5 (and possibly other) packages
**Describe the bug**
HDF5 does not build due to a git checkout error seemingly.

**To Reproduce**
Happens on my M1 Macbook. Building using GPU branch of `MFC-develop` and `release-cpu`. Error is:

```
> > > Package silo requires hdf5.
> > > > Package hdf5:
> > > > > Checking out 4aa40365623cf35643b262781f92578220c42bbb...

FATAL ERROR> Failed to execute command "cd "/Users/spencer/Downloads/MFC-develop/build/common/src/hdf5" && git checkout
"4aa40365623cf35643b262781f92578220c42bbb" >> "/Users/spencer/Downloads/MFC-develop/build/common/log/hdf5.log" 2>&1".
We apologize for the inconvenience. If you believe this is an issue with MFC, please visit
https://github.com/MFlowCode/MFC-develop/issues to file an issue.
```

which fails with 

```
Cloning into '/Users/spencer/Downloads/MFC-develop/build/common/src/hdf5'...
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

error: The following untracked working tree files would be overwritten by checkout:
```

### PR DESCRIPTION
**Pull request by henryleberre**
This pull request includes:
- [Closes #131] A switch to the CMake build system generator to improve:
  - Handle cross-platform compilations (\*nix, macOS, and (partially) Windows).
  - Dependency management (fetches and compiles dependencies).
  - Locating, finding, and using libraries and compiler features (e.g. MPI, OpenACC, Link Time Optimization (LTO/IPO)).
  - Support of various compilers & set their flags.
  - Handling of Fypp pre-processing (without copying directories and time-data).
  - Maintainability of the build system. 
  - Included LLNL/Silo#262
- The `--case-optimization` option which enables certain case parameters to be inserted as parameters/constants when building MFC Simulation. This option can significantly improve the performance of some OpenACC kernels.
- Regular and OpenACC-accelerated build targets co-exist. This effectively "merges" the master and GPU branches.
- Fypp now generates `.f90` files to an easily-accessible `src/<code name>/autogen` folder.
- A Docker container environment to build/test MFC regardless of host operating system.
  - I currently host a Docker image on DockerHub ([here](https://hub.docker.com/repository/docker/henryleberre/mfc))
- Tests no longer attempt to use `srun` and the `-g 1` is passed to `./mfc.sh run` when testing in mode whose name contains "gpu".
- [Closes #106] Cuda is no longer required when building on CPUs. Although if NVHPC is present, we still link to NvToolsExt.
- [Closes #18] Files that were generally shared between codes have been merged and moved to `src/common`. These include the following modules:
  - `m_compile_specific`
  - `m_derived_types`
More files could be added, especially `m_variables_conversion.f90` but most others require the heavy use of (often nested) conditional branches in preprocessor statements to handle each code. 
- The Python CLI interface is more accommodating to regular users, only serving as a front for CMake in the build process (except for `--case-optimization` - though one could easily do it by hand if provided an example `case.fpp` file).
- The Batch execution engine for `mfc.sh run` now forwards loaded modules when generating the final batch script from the templates.
- [Closes #21] Documentation is now auto-building and publishing using a new Doxygen-theme. This system is fully integrated with CMake, `./mfc.sh build`, and Github workflows. The user guide has been converted to Markdown and is hosted on the main website. CMake first runs each file through Fypp, copies relevant directories to a staging area within CMake current binary directory, runs Doxygen, and finally installs the documentation. Thus, documentation will only be rebuilt if any relevant files change.
- All MFC codes can be built using Intel compilers, even natively on Microsoft Windows.
- [Closes #113] @anandrdbz added cuFFT on GPUs. Regular FFT is used for CPUs.
- @anandrdbz added cuTENSOR. It is added as optional in CMake since it usually can't automatically be found by CMake or the linker. If cuTENSOR is not found, a legible warning is produced, and the code compiles and runs without support for `cu_tensor=T`.
- Building without MPI is allowed, passing `--no-mpi` to `mfc.sh`, which passes `-DMFC_WITH_MPI=OFF` to CMake, which does not set the `MFC_MPI` preprocessor definition, thereby instructing the code not to reference MPI.
- Requesting `mfc.sh` not build a specific dependency and instruct CMake to search the system for it is possible using the `--no-<target name>` options.
- When creating a job, it is often useful to inspect the generated batch file before submitting it. The `--dry-run` option of `./mfc.sh run` goes through the usual process of building as well as creating input files and batch files, but it doesn't submit them.
- The `-v` (aka `--verbose`) option instructs CMake to require the build system (Ninja, Make, ..) to print verbose output.
- When compiling for GPUs, we ask NVHPC to keep kernel files (PTX, (LLVM IR?) source, and binary) so that we can inspect them when inquiring about performance.
- We found an uncountable number of novel bugs in both the NVIDIA NVHPC SDK compilers that we ultimately resolved or worked around.
- Added a [CITATION.cff](https://github.com/henryleberre/MFC/blob/GPU/CITATION.cff) file.
- ...

Testing Progress:
- Local (x86) machine ✅
- Intel & ARM-based Apple macs ✅
- ORNL Summit ✅ + Ascent & Wombat (@anandrdbz)
- SDSC Expanse ⚠️: Interactive & Batch nodes were behaving strangely the past few days. 
- PSC Bridges2 ✅
- GT Wingtip#3 ✅

Build times (starting from a new clone of MFC) on GT Wingtip#3 (with CMake + Ninja) are more than 2x as fast as they used to be, in both `release-gpu` and `release-cpu` nodes, taking respectively 10 and 6.5 minutes. Ninja gets set as the default build system if it is available since it is much faster than GNU Make.

Since the current and newer build systems aren't compatible, `mfc.sh` will tell users to delete the relevant folders in order to upgrade. The lock file now only consists of two variables, one for the mode, and one to keep track of the build system changes (to tell users there was a breaking change).

The CPU and GPU versions of the code pass all 136 tests.

Credit: @henryleberre and @anandrdbz.

### CODE REVIEW

**Comment by sbryngelson** [comment]
Looks quite good! Builds fine on my M1 Mac. Before merging we should have all `samples/` working. I tested a few sporadically, which seemed to work. Some of the 2D ones didn't work because they probably weren't converted to the newer format. I did 
get a weird error for this one: `./mfc.sh run samples/2D_shearlayer/case.py`

```
Running simulation:

      $ mpirun -np 1  "/Users/spencer/Downloads/MFC-develop/build/install/bin/simulation"

At line 115 of file /Users/spencer/Downloads/MFC-develop/src/simulation_code/autogen/m_start_up.f90 (unit = 1, file = './simulation.inp')
Fortran runtime error: Cannot match namelist object name .0t_step_save

Error termination. Backtrace:

Could not print backtrace: executable file is not an executable
#0  0x105659617
#1  0x10565a1b7
#2  0x10565ab33
#3  0x10573a957
#4  0x105742ec3
#5  0x105743177
#6  0x104d9a92b
#7  0x104daa2cb
#8  0x104e4770f
```

**Comment by sbryngelson** [comment]
Question: Was there testing of the batch and interactive mode across a few different systems? i.e., Summit, Bridges2, and Phoenix should be sufficient.

**Comment by sbryngelson** [comment]
This case doesn't run on phoenix
```
login-phoenix-3: p-sbryngelson3-0/MFC $ ./mfc.sh  run ./samples/1D_bubblescreen/case.py
      ___            ___          ___
     /__/\          /  /\        /  /\       sbryngelson3@login-phoenix-3.pace.gatech.edu [Linux]
    |  |::\        /  /:/_      /  /:/       ----------------------------------------------------
    |  |:|:\      /  /:/ /\    /  /:/
  __|__|:|\:\    /  /:/ /:/   /  /:/  ___
 /__/::::| \:\  /__/:/ /:/   /__/:/  /  /\   --jobs:    1
 \  \:\~~\__\/  \  \:\/:/    \  \:\ /  /:/   --mode:    release-cpu
  \  \:\         \  \::/      \  \:\  /:/    --targets: pre_process, simulation, and post_process
   \  \:\         \  \:\       \  \:\/:/
    \  \:\         \  \:\       \  \::/
     \__\/          \__\/        \__\/       $ ./mfc.sh [build, run, test, clean] --help

Run
  Acquiring ./samples/1D_bubblescreen/case.py...
  Configuration:
    Input               ./samples/1D_bubblescreen/case.py
    Job Name      (-#)  unnamed
    Engine        (-e)  interactive
    Nodes         (-N)  1
    CPUs (/node)  (-n)  1
    GPUs (/node)  (-g)  0
    MPI Binary    (-b)  mpirun

  Running pre_process:
    Building pre_process:

      $ cd "/storage/coda1/p-sbryngelson3/0/sbryngelson3/MFC/build/pre_process" && cmake --build . -j 1 --target pre_process --config Release

[100%] Built target pre_process

      $ cd "/storage/coda1/p-sbryngelson3/0/sbryngelson3/MFC/build/pre_process" && cmake --install .

-- Install configuration: "Release"
-- Installing: /storage/coda1/p-sbryngelson3/0/sbryngelson3/MFC/build/install/bin/pre_process

    Running pre_process:

      $ mpirun -np 1  "/storage/coda1/p-sbryngelson3/0/sbryngelson3/MFC/build/install/bin/pre_process"

 R0 weights:    1.00000000000000
 R0 abscissas:    1.00000000000000
 In convert, nbub:  2.387324146378430E-013
 Final Time  7.826000000000000E-003

      Done (in 0:00:00.569470)

  Running simulation:
    Building simulation:

      $ cd "/storage/coda1/p-sbryngelson3/0/sbryngelson3/MFC/build/simulation" && cmake --build . -j 1 --target simulation --config Release

[100%] Built target simulation

      $ cd "/storage/coda1/p-sbryngelson3/0/sbryngelson3/MFC/build/simulation" && cmake --install .

-- Install configuration: "Release"
-- Installing: /storage/coda1/p-sbryngelson3/0/sbryngelson3/MFC/build/install/bin/simulation

    Running simulation:

      $ mpirun -np 1  "/storage/coda1/p-sbryngelson3/0/sbryngelson3/MFC/build/install/bin/simulation"

          -3
         100           0           0
 R0 weights:    1.00000000000000
 R0 abscissas:    1.00000000000000
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
simulation         0000000000724E53  for__signal_handl     Unknown  Unknown
```

**Comment by anandrdbz** [comment]
All of the sample cases should now run using either gcc or nvhpc (There were some issues with run_time_info which are now fixed). 


As far as the issue on phoenix is concerned, this seems to be a problem with the intel compiler on phoenix and not the specific sample case as all the test cases give the same bug as well. Switching to gcc alleviates the issue.

**Comment by henryleberre** [comment]
@sbryngelson With our recent fixes, MFC is mergeable in my opinion. All tests and samples run on CPUs and GPUs (see caveats below), using GNU, Intel, and NVHPC compilers, no matter the MPI implementation (IntelMPI, MVAPICH, and OpenMPI), on Linux, macOS, and even Windows.

<p align="justify">
I've applied patches to our convenience scripts for loading modules and running/submitting jobs. MFC builds everywhere but some systems require a bit of experimentation to get it running. Although I haven't been able to try (and get to work) all possible combinations of computer, compiler, MPI vendor, release mode, and execution mode, we have good reason to believe that the difficulties lie in our interaction with the system, rather than our code. If any issue arises in a particular environment, we can handle it when we need to. I'm mostly referring to Bridges2 and Expanse. From my testing, it seems to work _as well as_ the current MFC-develop in its capacity to run on various computers. Some systems' modules appear to be broken, or at least incompatible with modules that should be. Also, documentation on best practices is rather limited and obsolete. Expanse's documentation still refers to PGI for GPUs with its bundled MPI wrapper, even though NVHPC has replaced it, and its wrapper, although present, is not configured to work when loading the module. Fortunately, another advantage of using CMake is that it has much more support for user intervention in the configuration process.
</p>

We can merge to the GPU branch first and then decide when we make it the default branch.

**Comment by henryleberre** [comment]
@sbryngelson Definitely. Most systems have newer releases, it’s just Bridges2 and Phoenix that are out of date as far as I can remember. I will see if I can just download the latest binary release from https://cmake.org/download/ instead of building from scratch.

**Comment by sbryngelson** [comment]
> @sbryngelson Definitely. Most systems have newer releases, it’s just Bridges2 and Phoenix that are out of date as far as I can remember. I will see if I can just download the latest binary release from https://cmake.org/download/ instead of building from scratch.

Keep in mind that there are many other computers, clusters, and supercomputers out there that folks use (just not us). If it's out of date on 20% of the computers we use, it's likely out of date for 1/5 of the people who might want to use MFC.

**Comment by sbryngelson** [comment]
Testing doesn't work on Expanse: 

```
[I]login01: project-bryngelsonPI/MFC $ ./mfc.sh test -j 1
      ___            ___          ___
     /__/\          /  /\        /  /\       bryngel@login01 [Linux]
    |  |::\        /  /:/_      /  /:/       -----------------------
    |  |:|:\      /  /:/ /\    /  /:/
  __|__|:|\:\    /  /:/ /:/   /  /:/  ___
 /__/::::| \:\  /__/:/ /:/   /__/:/  /  /\   --jobs:    1
 \  \:\~~\__\/  \  \:\/:/    \  \:\ /  /:/   --mode:    release-cpu
  \  \:\         \  \::/      \  \:\  /:/
   \  \:\         \  \:\       \  \:\/:/
    \  \:\         \  \:\       \  \::/
     \__\/          \__\/        \__\/       $ ./mfc.sh [build, run, test, clean] --help

Building pre_process:

  $ cd "/expanse/lustre/projects/cit193/bryngel/MFC/build/pre_process" && cmake --build . -j 1 --target pre_process --config Release

[100%] Built target pre_process

  $ cd "/expanse/lustre/projects/cit193/bryngel/MFC/build/pre_process" && cmake --install .

-- Install configuration: "Release"
-- Installing: /expanse/lustre/projects/cit193/bryngel/MFC/build/install/bin/pre_process
-- Set runtime path of "/expanse/lustre/projects/cit193/bryngel/MFC/build/install/bin/pre_process" to ""

Building simulation:

  $ cd "/expanse/lustre/projects/cit193/bryngel/MFC/build/simulation" && cmake --build . -j 1 --target simulation --config Release

[100%] Built target simulation

  $ cd "/expanse/lustre/projects/cit193/bryngel/MFC/build/simulation" && cmake --install .

-- Install configuration: "Release"
-- Installing: /expanse/lustre/projects/cit193/bryngel/MFC/build/install/bin/simulation
-- Set runtime path of "/expanse/lustre/projects/cit193/bryngel/MFC/build/install/bin/simulation" to ""

Test | from 5EB1467A to 177B85F6 (136 tests)

   tests/UUID    Summary

        ___            ___          ___
       /__/\          /  /\        /  /\       bryngel@login01 [Linux]
      |  |::\        /  /:/_      /  /:/       -----------------------
      |  |:|:\      /  /:/ /\    /  /:/
    __|__|:|\:\    /  /:/ /:/   /  /:/  ___
   /__/::::| \:\  /__/:/ /:/   /__/:/  /  /\   --jobs:    1
   \  \:\~~\__\/  \  \:\/:/    \  \:\ /  /:/   --mode:    release-cpu
    \  \:\         \  \::/      \  \:\  /:/    --targets: pre_process and simulation
     \  \:\         \  \:\       \  \:\/:/
      \  \:\         \  \:\       \  \::/
       \__\/          \__\/        \__\/       $ ./mfc.sh  --help

  Run
    Acquiring /expanse/lustre/projects/cit193/bryngel/MFC/tests/5EB1467A/case.py...
    Configuration:
      Input               /expanse/lustre/projects/cit193/bryngel/MFC/tests/5EB1467A/case.py
      Job Name      (-#)  unnamed
      Engine        (-e)  interactive
      Nodes         (-N)  1
      CPUs (/node)  (-n)  1
      GPUs (/node)  (-g)  0
      MPI Binary    (-b)  srun

    Running pre_process:
      Running pre_process:

        $ srun  --ntasks-per-node 1  "/expanse/lustre/projects/cit193/bryngel/MFC/build/install/bin/pre_process"

  srun: error: Unable to allocate resources: Time limit specification required, but not provided


  Error: Failed to execute command "cd "/expanse/lustre/projects/cit193/bryngel/MFC/tests/5EB1467A" && srun  --ntasks-per-node 1
  "/expanse/lustre/projects/cit193/bryngel/MFC/build/install/bin/pre_process"".

  ./mfc.sh: line 186: 2323068 Terminated              python3 "$(pwd)/toolchain/main.py" "$@"



Error: Test tests/5EB1467A: 1D (m=299,n=0,p=0) -> bc=-1: Failed to execute MFC. Above is the output of MFC.
You can find the output in /expanse/lustre/projects/cit193/bryngel/MFC/tests/5EB1467A/out.txt, and the case dictionary in
/expanse/lustre/projects/cit193/bryngel/MFC/tests/5EB1467A/case.py.

./mfc.sh: line 186: 2322902 Terminated              python3 "$(pwd)/toolchain/main.py" "$@"
```

**Comment by sbryngelson** [comment]
If I get onto an interactive node I end up with failing tests:
```
[I]exp-9-36: bryngel/MFC $ ./mfc.sh test -j 8
      ___            ___          ___
     /__/\          /  /\        /  /\       bryngel@exp-9-36 [Linux]
    |  |::\        /  /:/_      /  /:/       ------------------------
    |  |:|:\      /  /:/ /\    /  /:/
  __|__|:|\:\    /  /:/ /:/   /  /:/  ___
 /__/::::| \:\  /__/:/ /:/   /__/:/  /  /\   --jobs:    8
 \  \:\~~\__\/  \  \:\/:/    \  \:\ /  /:/   --mode:    release-cpu
  \  \:\         \  \::/      \  \:\  /:/
   \  \:\         \  \:\       \  \:\/:/
    \  \:\         \  \:\       \  \::/
     \__\/          \__\/        \__\/       $ ./mfc.sh [build, run, test, clean] --help

Building pre_process:

  $ cd "/home/bryngel/MFC/build/pre_process" && cmake --build . -j 8 --target pre_process --config Release

[100%] Built target pre_process

  $ cd "/home/bryngel/MFC/build/pre_process" && cmake --install .

-- Install configuration: "Release"
-- Installing: /home/bryngel/MFC/build/install/bin/pre_process

Building simulation:

  $ cd "/home/bryngel/MFC/build/simulation" && cmake --build . -j 8 --target simulation --config Release

[100%] Built target simulation

  $ cd "/home/bryngel/MFC/build/simulation" && cmake --install .

-- Install configuration: "Release"
-- Installing: /home/bryngel/MFC/build/install/bin/simulation
-- Set runtime path of "/home/bryngel/MFC/build/install/bin/simulation" to ""

Test | from 5EB1467A to 177B85F6 (136 tests)

   tests/UUID    Summary




Error:     tests/A9612DE8: Failed to execute MFC [1D (m=299,n=0,p=0) -> bc=-4]. Above is the output of MFC.
    You can find the output in /home/bryngel/MFC/tests/A9612DE8/out.txt, and the case dictionary in /home/bryngel/MFC/tests/A9612DE8/case.py.

./mfc.sh: line 146: 3931867 Terminated              python3 "$(pwd)/toolchain/mfc/main.py" "$@"
```

**Comment by henryleberre** [comment]
@sbryngelson I pushed the code in `mfc.sh` that installs a recent version of CMake if either:
- CMake is not installed
- CMake is not compatible (its version is lower than our minimum required)

It works for x86_64 (aka amd64) and arm (aarch64) Linux. We attempt to download the correct file using the output of `uname -m` for the system's architecture. It works on Bridges2, Expanse, and Wombat (tested for arm). If an error occurs, the user is given instructions/hints on what to do (build from scratch, modules, spack, ...). It is fully transparent like the Python virtualenv that we use. Thus, the user might not even realize it is a thing. The CMake binaries are installed in the prefix `build/cmake/`.

As for the issue on Expanse, I think it's because you aren't using the modules from `. ./mfc.sh load`. Expanse is quite picky and the modules the script provides are those I personally used while testing (sometimes after quit some struggles). However, you might want to `git pull` first because I had one of my (personal) scripts on Expanse that automatically loaded ìntel-mpi` - which is not included in `load.sh`.

The batch system appears to be hanging for me right now on Expanse, but manually using `srun` with the right `.inp` input files generated by `./mfc.sh test`, does run MFC without failing.

**Pull request merged**
